version: "3"
services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    command: sh -c "php /var/www/html/conf/init_db.php && a2enmod rewrite && apache2-foreground"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres-data: